"""
diagnose_mechanistic.py
-----------------------
Eyes-on diagnostic for the mechanistic I_T + I_h model BEFORE/AFTER fitting.

Overlays the model PD / anti-PD / 90-deg traces on the REAL population PSTH,
shows the space-time heatmap, and runs the ablation test (g_T = g_h = 0) so you
can confirm the slow component (SC) is generated by the intrinsic channels and
not by the input or the loss.

    from diagnose_mechanistic import diagnose
    diagnose(stage1_frozen, stage2_params)   # stage2_params in PARAM_NAMES[7:] order
"""

import numpy as np
import matplotlib.pyplot as plt

import optimization_engine as oe
from vivo_target import load_vivo_psth

_S1_KEYS = ["tau_E", "tau_I", "I_baseline", "J1", "KAPPA_E", "W_IE", "KAPPA_I", "W_EI", "I_HD"]
# Index of g_T / g_h inside the stage-2 parameter vector (for ablation).
_GT_IDX, _GH_IDX = 4, 9


def _run(stage1_frozen, stage2_params):
    s1 = [stage1_frozen[k] for k in _S1_KEYS]
    return oe.run_model_stim(*s1, *stage2_params)


def _r2(model, target):
    ss_res = np.sum((target - model) ** 2)
    ss_tot = np.sum((target - np.mean(target)) ** 2)
    return 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan


def diagnose(stage1_frozen, stage2_params, vivo=None, title="", t_lo=None, t_hi=None):
    """Plot model-vs-data overlay + heatmap + ablation. Returns R^2 of PD fit.

    t_lo / t_hi set the plotting window (ms); default to the fit window
    (oe.WIN_LO/WIN_HI). Pass e.g. t_hi=700 to watch the attractor recover. R^2 is
    always computed on the fit window, not the plotting window.
    """
    if vivo is None:
        vivo = load_vivo_psth()
    bins, vrate, vsmooth = vivo
    t_lo = oe.WIN_LO if t_lo is None else t_lo
    t_hi = oe.WIN_HI if t_hi is None else t_hi

    t, rates = _run(stage1_frozen, stage2_params)
    pd = rates[:, oe._IDX_0]
    anti = rates[:, oe._IDX_180]
    idx_90 = int(np.argmin(np.abs(oe.THETA - np.pi / 2)))
    pd90 = rates[:, idx_90]

    # Ablation: zero both intrinsic conductances -> SC must collapse to baseline.
    abl = list(stage2_params)
    abl[_GT_IDX] = 0.0
    abl[_GH_IDX] = 0.0
    _, rates_abl = _run(stage1_frozen, abl)
    pd_abl = rates_abl[:, oe._IDX_0]

    # R^2 of PD trace vs raw PSTH on the FIT window (independent of plot window).
    win = (bins >= oe.WIN_LO) & (bins <= oe.WIN_HI)
    model_at_vivo = np.interp(bins[win], t, pd)
    r2 = _r2(model_at_vivo, vrate[win])

    vwin = (bins >= t_lo) & (bins <= t_hi)  # vivo data over the plot window

    fig = plt.figure(figsize=(13, 9))
    gs = fig.add_gridspec(2, 2)

    # (1) PD model vs real PSTH
    ax = fig.add_subplot(gs[0, 0])
    ax.plot(bins[vwin], vrate[vwin], color="0.4", lw=1.5, label="in vivo (raw)")
    ax.plot(bins[vwin], vsmooth[vwin], color="0.4", ls="--", lw=1.5, label="in vivo (smooth)")
    ax.plot(t, pd, color="crimson", lw=2.2, label="model PD (0deg)")
    ax.plot(t, pd_abl, color="crimson", ls=":", lw=1.5, label="model PD, g_T=g_h=0 (ablation)")
    ax.set_xlim(t_lo, t_hi)
    ax.set_xlabel("time rel. stim (ms)"); ax.set_ylabel("firing rate (Hz)")
    ax.set_title(f"PD vs biology   R2={r2:.3f}")
    ax.legend(fontsize=8); ax.grid(alpha=0.3)

    # (2) PD vs anti-PD vs 90deg (emergence of PD-only SC)
    ax = fig.add_subplot(gs[0, 1])
    ax.plot(t, pd, color="crimson", lw=2, label="PD (0deg)")
    ax.plot(t, pd90, color="orange", lw=2, label="90deg")
    ax.plot(t, anti, color="navy", lw=2, label="anti-PD (180deg)")
    ax.set_xlim(t_lo, t_hi)
    ax.set_xlabel("time rel. stim (ms)"); ax.set_ylabel("firing rate (Hz)")
    ax.set_title("directional traces (SC should be PD-only)")
    ax.legend(fontsize=8); ax.grid(alpha=0.3)

    # (3) space-time heatmap (+ FWHM-over-time overlay to read out recovery)
    ax = fig.add_subplot(gs[1, 0])
    tm = (t >= t_lo) & (t <= t_hi)
    im = ax.imshow(
        rates[tm, :].T, aspect="auto", origin="lower",
        extent=[t_lo, t_hi, -180, 180], cmap="magma", vmin=0, vmax=100,
    )
    # FWHM(t) (deg) traced on the same axis -> see if the bump re-narrows.
    deg = np.rad2deg(oe.THETA)
    fwhm = np.array([
        ((row >= row.max() / 2).sum() * 360.0 / oe.N) if row.max() > 1 else 0.0
        for row in rates[tm, :]
    ])
    ax.plot(t[tm], fwhm - 180, color="cyan", lw=1.2, alpha=0.8, label="FWHM (deg)")
    ax.axvline(0, color="w", ls="--", alpha=0.5)
    ax.set_xlabel("time rel. stim (ms)"); ax.set_ylabel("preferred dir (deg)")
    ax.set_title("network activity (cyan = bump FWHM)")
    ax.legend(fontsize=7, loc="upper right")
    fig.colorbar(im, ax=ax, label="Hz")

    # (4) channel decomposition: I_T-only vs I_h-only rebound contribution
    ax = fig.add_subplot(gs[1, 1])
    it_only = list(stage2_params); it_only[_GH_IDX] = 0.0   # g_h = 0 -> I_T only
    ih_only = list(stage2_params); ih_only[_GT_IDX] = 0.0   # g_T = 0 -> I_h only
    _, r_it = _run(stage1_frozen, it_only)
    _, r_ih = _run(stage1_frozen, ih_only)
    ax.plot(t, pd, color="crimson", lw=2, label="full")
    ax.plot(t, r_it[:, oe._IDX_0], color="seagreen", lw=1.6, label="I_T only (g_h=0)")
    ax.plot(t, r_ih[:, oe._IDX_0], color="purple", lw=1.6, label="I_h only (g_T=0)")
    ax.plot(t, pd_abl, color="0.5", ls=":", lw=1.4, label="neither")
    ax.set_xlim(t_lo, t_hi)
    ax.set_xlabel("time rel. stim (ms)"); ax.set_ylabel("PD firing rate (Hz)")
    ax.set_title("channel decomposition (timescale separation)")
    ax.legend(fontsize=8); ax.grid(alpha=0.3)

    fig.suptitle(title or "Mechanistic I_T + I_h diagnostic", fontsize=13)
    fig.tight_layout()
    plt.show()

    print(f"PD fit R2 = {r2:.3f}")
    sc = (t > 40) & (t < 300)
    print(f"SC-window PD max: full {pd[sc].max():.1f} Hz | ablation {pd_abl[sc].max():.1f} Hz")
    print(f"SC-window anti-PD max: {anti[sc].max():.1f} Hz (should be near baseline)")
    return r2


if __name__ == "__main__":
    # Hand-picked starting params (pre-optimization sanity check).
    frozen = dict(tau_E=20.0, tau_I=8.0, I_baseline=20.0, J1=20.0,
                  KAPPA_E=8.0, W_IE=12.0, KAPPA_I=2.0, W_EI=4.0)
    # A_fast, fc_dur, stim_delay, reversal, g_T,V_half_T,k_T,tau_hT,E_Ca, g_h,V_half_h,tau_h
    p = [1500.0, 3.0, 10.0, -35.0, 40.0, 5.0, 8.0, 40.0, 120.0, 15.0, -10.0, 250.0]
    diagnose(frozen, p, title="I_T + I_h diagnostic (hand-picked params)")
