[package]
name = "rustsorter"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui_plot = "0.32.1"
hdf5 = "0.8.1"
hdf5-sys = "0.8.1"
numpy = "0.25.0"
pyo3 = "0.25.0"
rand = "0.9.1"
random = "0.14.0"
